#!/bin/bash

source /usr/share/yunohost/helpers

main_domain=$(cat /etc/yunohost/current_host)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
if ynh_app_upgrading_from_version_before 6.15.3~ynh1; then
    ynh_script_progression "Fixing up directory structure..."
    mkdir $install_dir/traccar
    pushd $install_dir
      shopt -s extglob
      mv !(traccar) traccar
      shopt -u extglob
    popd
fi

ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir/traccar" --full_replace --keep="conf/traccar.xml"
ynh_setup_source --dest_dir="$install_dir/jre" --source_id="jre"

chown -R $app:$app $install_dir

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Modern GPS tracking platform" --log="/var/log/$app/$app.log"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating configuration..."

#ynh_config_add --template="traccar.xml" --destination="$install_dir/conf/traccar.xml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
